version: '3'

services:
  reverse-proxy:
    restart: always
    image: traefik:latest
    command: --api --docker
    networks:
      - web
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    image: mongo:latest
    networks:
      - web
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/var/lib/mongodb/data

  orchestrator:
    build: ./orchestrator
    networks:
      - web
    ports:
      - "9000:9000"
    labels:
      - "traefik.frontend.rule=Host:orchestrator.localhost"
    environment:
      - EB_MONGO_HOST=mongodb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - reverse-proxy
      - mongodb

networks:
  web:
    external:
      name: traefik_default
