export default {
  MAP_WIDTH: 6000,
  MAP_HEIGHT: 6000,

  SOCKET_PORT: process.env.EB_SERVER_PORT || 4242,
  SPEED: 5,
  BASE_ANGLE: Math.PI * 200,

  GAMELOOP_RATE: 16,
  MAP_RECT_WIDTH: 150,
  MAP_RECT_HEIGHT: 150,

  INITIAL_FOOD_COUNT: 700,
  INITIAL_FOOD_VALUE: 500,
  INITIAL_SCALE: 1,

  MAX_SIZE: 300,
  MAX_LEN: 300,
  ORCHESTRATOR_URL: process.env.EB_ORCHESTRATOR_URL || 'localhost:9000',
  ORCHESTRATOR_SECRET: process.env.EB_ORCHESTRATOR_SECRET || 'secret',
};
